#!/usr/bin/bash

# Make sure you have setup nvm in https://typicode.github.io/husky/how-to.html#startup-files

changed_files="$(git diff --cached --name-only --diff-filter=ACMR)"

if [[ -n "$changed_files" ]]; then
    npx prettier "$changed_files" --write --ignore-unknown
    git update-index --again
fi
